version: '3.8'

services:
  domain-analysis-service:
    container_name: "doman_analysis"
    image: "doman_analysis:latest"
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development